services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: development-stage # simply change this to production-stage for production
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    command: pnpm start:dev
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - .:/app # sync code changes with container, only for development
    networks:
      - app-network
  
  redis:
    image: redis:latest
    ports:
      - "${REDIS_PORT}:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - app-network

  postgres:
    image: postgres:15 
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    
networks:
  app-network:
    name: ${APP_NAME}-network
    driver: bridge

volumes:
  postgres_data:
  redis_data:
