export enum ErrorCode {
    NO_FILE_FOUND = 'NO_FILE_FOUND',
    FILE_NOT_FOUND = 'FILE_NOT_FOUND',
    FILE_ALREADY_EXISTS = 'FILE_ALREADY_EXISTS',
    DIRECTORY_NOT_FOUND = 'DIRECTORY_NOT_FOUND',
    DIRECTORY_ALREADY_EXISTS = 'DIRECTORY_ALREADY_EXISTS',
    UPLOAD_FAILED = 'UPLOAD_FAILED',
    DELETE_FAILED = 'DELETE_FAILED',
    GET_FAILED = 'GET_FAILED',
    GET_PRESIGNED_URL_FAILED = 'GET_PRESIGNED_URL_FAILED',
    LIST_FILES_FAILED = 'LIST_FILES_FAILED',
}